import uuid
from datetime import datetime

from pydantic import BaseModel, ConfigDict


# --- Artifact schemas ---

class ArtifactOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    workspace_id: uuid.UUID
    agent_name: str
    artifact_type: str
    title: str
    content: str
    content_format: str
    version: int
    created_at: datetime


# --- Workspace schemas ---

class WorkspaceOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    application_id: uuid.UUID
    user_id: uuid.UUID
    status: str
    created_at: datetime
    updated_at: datetime
    artifacts: list[ArtifactOut] = []


class WorkspaceCreate(BaseModel):
    application_id: uuid.UUID


# --- Pipeline schemas ---

class PipelineRunOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    workspace_id: uuid.UUID
    pipeline_type: str
    status: str
    current_agent: str | None = None
    completed_agents: str
    error_message: str | None = None
    created_at: datetime
    updated_at: datetime


class PipelineStartRequest(BaseModel):
    pipeline_type: str = "full"  # "full" or "quick"


# --- Preflight schemas ---

class PreflightItem(BaseModel):
    """A single data requirement for an agent."""
    name: str
    description: str
    status: str  # "ready", "missing", "partial"
    source: str  # where to get it: "profile", "job_listing", "workspace", "user_input"
    detail: str | None = None  # specific guidance for the user


class PreflightResult(BaseModel):
    """Result of an agent's preflight check."""
    agent_name: str
    ready: bool
    items: list[PreflightItem]
    suggestion: str | None = None  # what the agent suggests the user do first


# --- Agent task schemas (for user-directed mode) ---

class AgentTaskRequest(BaseModel):
    """Request to run an agent task against a workspace."""
    agent_name: str
    task_type: str | None = None  # optional override; defaults to agent's primary task
    additional_instructions: str | None = None  # user-provided guidance


class AgentTaskResult(BaseModel):
    """Result of an agent task execution."""
    agent_name: str
    artifacts_created: list[ArtifactOut]
    summary: str
    next_suggested_agent: str | None = None
    preflight_warnings: list[PreflightItem] = []


# --- Application Form schemas (Auto-Fill modal) ---

class ApplicationFormField(BaseModel):
    """A single field in the application form."""
    key: str
    label: str
    value: str
    field_type: str = "text"  # text, textarea, select, email, tel, url
    options: list[str] | None = None  # for select fields
    required: bool = True
    section: str = "personal"  # personal, professional, additional


class ApplicationFormData(BaseModel):
    """Full application form data generated by AI."""
    fields: list[ApplicationFormField]
    job_title: str
    job_company: str


class ApplicationFormSubmit(BaseModel):
    """User-edited form data submitted for review or submission."""
    fields: list[ApplicationFormField]


class CompletenessCheckResult(BaseModel):
    """Result of a completeness check on the application form."""
    complete: bool
    total_fields: int
    filled_fields: int
    issues: list[dict]  # [{field_key, field_label, issue}]


class BestFitReviewResult(BaseModel):
    """Result of an AI best-fit review of the application."""
    score: int  # 1-100
    verdict: str  # "strong", "good", "needs_work"
    summary: str
    strengths: list[str]
    improvements: list[dict]  # [{field_key, field_label, current_value, suggestion}]


# --- Chatbot simulation schemas (Auto-Fill modal, chatbot mode) ---

class DetectedMethodResult(BaseModel):
    """Result of detecting the application method for a job."""
    method: str  # form, chatbot, email, redirect, api_portal, unknown
    platform: str
    job_title: str
    job_company: str
    job_url: str


class ChatbotQuestionItem(BaseModel):
    """A single chatbot question with AI-suggested answer."""
    index: int
    question: str
    suggested_answer: str
    field_name: str = "unknown"
    confidence: str = "medium"  # high, medium, low
    approved_answer: str | None = None  # user's final answer after review
    status: str = "pending"  # pending, accepted, edited, skipped


class ChatbotSimulationResult(BaseModel):
    """Result of simulating the chatbot to collect questions + suggestions."""
    method: str
    platform: str
    job_title: str
    job_company: str
    job_url: str
    questions: list[ChatbotQuestionItem]
    total_questions: int


class ChatbotSubmitRequest(BaseModel):
    """User-approved answers to submit to the real chatbot."""
    answers: list[ChatbotQuestionItem]


class ChatbotSubmitResult(BaseModel):
    """Result of driving the real chatbot with approved answers."""
    success: bool
    messages_exchanged: int
    data_submitted: dict
    verification: list[dict]  # [{simulated, live, match, score}]
    error: str | None = None
    completed: bool = False
